In [1]:
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import seaborn as sns
%matplotlib inline
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.linear_model import LogisticRegression
from sklearn.naive_bayes import GaussianNB
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score,roc_auc_score, roc_curve,precision_score, recall_score, f1_score,confusion_matrix,classification_report

In [2]:
df=pd.read_csv(r"C:\Users\91876\Desktop\Python\Flask folder\Flask5\StudentsPerformance[1].csv")

In [3]:
df.head()

gender race/ethnicity parental level of education         lunch  \
0  female        group B           bachelor's degree      standard   
1  female        group C                some college      standard   
2  female        group B             master's degree      standard   
3    male        group A          associate's degree  free/reduced   
4    male        group C                some college      standard   

  test preparation course  math score  reading score  writing score  
0                    none          72             72             74  
1               completed          69             90             88  
2                    none          90             95             93  
3                    none          47             57             44  
4                    none          76             78             75

In [4]:
df.shape

(1000, 8)

In [5]:
df.dtypes

gender                         object
race/ethnicity                 object
parental level of education    object
lunch                          object
test preparation course        object
math score                      int64
reading score                   int64
writing score                   int64
dtype: object

In [6]:
df.describe()

math score  reading score  writing score
count  1000.00000    1000.000000    1000.000000
mean     66.08900      69.169000      68.054000
std      15.16308      14.600192      15.195657
min       0.00000      17.000000      10.000000
25%      57.00000      59.000000      57.750000
50%      66.00000      70.000000      69.000000
75%      77.00000      79.000000      79.000000
max     100.00000     100.000000     100.000000

In [7]:
df.isna().sum()

gender                         0
race/ethnicity                 0
parental level of education    0
lunch                          0
test preparation course        0
math score                     0
reading score                  0
writing score                  0
dtype: int64

In [8]:
df.duplicated().sum()

0

In [9]:
df.columns.values

array(['gender', 'race/ethnicity', 'parental level of education', 'lunch',
       'test preparation course', 'math score', 'reading score',
       'writing score'], dtype=object)

In [10]:
df['Total score']=df['math score'] + df['reading score'] + df['writing score']

In [11]:
df.gender.unique()

array(['female', 'male'], dtype=object)

In [12]:
df['race/ethnicity'].unique()

array(['group B', 'group C', 'group A', 'group D', 'group E'],
      dtype=object)

In [13]:
df['parental level of education'].unique()

array(["bachelor's degree", 'some college', "master's degree",
       "associate's degree", 'high school', 'some high school'],
      dtype=object)

In [14]:
df['lunch'].unique()

array(['standard', 'free/reduced'], dtype=object)

In [15]:
df['test preparation course'].unique()

array(['none', 'completed'], dtype=object)

In [16]:
df['math score'].unique()

array([ 72,  69,  90,  47,  76,  71,  88,  40,  64,  38,  58,  65,  78,
        50,  18,  46,  54,  66,  44,  74,  73,  67,  70,  62,  63,  56,
        97,  81,  75,  57,  55,  53,  59,  82,  77,  33,  52,   0,  79,
        39,  45,  60,  61,  41,  49,  30,  80,  42,  27,  43,  68,  85,
        98,  87,  51,  99,  84,  91,  83,  89,  22, 100,  96,  94,  48,
        35,  34,  86,  92,  37,  28,  24,  26,  95,  36,  29,  32,  93,
        19,  23,   8], dtype=int64)

In [17]:
df['reading score'].unique()

array([ 72,  90,  95,  57,  78,  83,  43,  64,  60,  54,  52,  81,  53,
        75,  89,  32,  42,  58,  69,  73,  71,  74,  70,  65,  87,  56,
        61,  84,  55,  44,  41,  85,  59,  17,  39,  80,  37,  63,  51,
        49,  26,  68,  45,  47,  86,  34,  79,  66,  67,  91, 100,  76,
        77,  82,  92,  93,  62,  88,  50,  28,  48,  46,  23,  38,  94,
        97,  99,  31,  96,  24,  29,  40], dtype=int64)

In [18]:
df['writing score'].unique()

array([ 74,  88,  93,  44,  75,  78,  92,  39,  67,  50,  52,  43,  73,
        70,  58,  86,  28,  46,  61,  63,  53,  80,  72,  55,  65,  38,
        82,  79,  83,  59,  57,  54,  68,  66,  62,  76,  48,  42,  87,
        49,  10,  34,  71,  37,  56,  41,  22,  81,  45,  36,  89,  47,
        90, 100,  64,  98,  51,  40,  84,  69,  33,  60,  85,  91,  77,
        27,  94,  95,  19,  35,  32,  96,  97,  99,  15,  30,  23],
      dtype=int64)

In [19]:
df['Total score'].unique()

array([218, 247, 278, 148, 229, 232, 275, 122, 195, 164, 135, 219, 220,
       161, 222, 263,  78, 134, 173, 198, 210, 151, 215, 225, 178, 211,
       205, 207, 217, 189, 193, 120, 266, 241, 238, 253, 170, 199, 176,
       190, 160, 182, 213, 248, 156, 214, 139, 242, 117, 175,  27, 112,
       192, 119, 206, 194, 181, 140, 174, 123, 239, 146, 115, 235, 216,
        97, 221, 138, 257, 187, 265, 274, 197, 287, 264, 166, 154, 163,
       299, 260, 272, 236, 268, 255, 130, 231, 240, 228, 201, 185, 147,
        94, 224, 293, 212, 150, 180, 234, 296, 155, 246, 200, 259, 158,
       184, 297, 204, 196, 145, 252, 168, 162, 153, 233, 237, 223, 142,
        90, 167, 245, 191, 277, 131, 249, 157, 244, 227, 282, 149, 270,
       186, 226, 129, 267, 230, 136, 183, 202, 250, 203,  70, 171, 271,
       143,  89, 177, 179,  93, 188, 280, 132, 124, 269, 169, 165, 256,
       172, 114, 289, 300, 258, 262,  95, 209, 243, 273, 276, 261, 208,
       104, 292, 279, 291,  69,  88, 251, 152, 144, 159, 113, 25

In [20]:
df.head()

gender race/ethnicity parental level of education         lunch  \
0  female        group B           bachelor's degree      standard   
1  female        group C                some college      standard   
2  female        group B             master's degree      standard   
3    male        group A          associate's degree  free/reduced   
4    male        group C                some college      standard   

  test preparation course  math score  reading score  writing score  \
0                    none          72             72             74   
1               completed          69             90             88   
2                    none          90             95             93   
3                    none          47             57             44   
4                    none          76             78             75   

   Total score  
0          218  
1          247  
2          278  
3          148  
4          229

### outlier analysis

In [21]:
def identify_outliers(col_name):
    i=col_name
    # calculate quartiles
    Q1=round(np.quantile(df[i],0.25),2)
    Q2=round(np.quantile(df[i],0.50),2)
    Q3=round(np.quantile(df[i],0.75),2)
    # compute inter quartile range
    IQR=Q3-Q1
    # determine outlier bound
    upper_bound=Q3+(1.5*IQR)
    lower_bound=Q1-(1.5*IQR)
    # conditions to determine outlier
    cond1=df[i]>upper_bound
    cond2=df[i]<lower_bound
    # apply the conditions to find outlier
    outlier=df[i][cond1|cond2] #series
    # retrun dataframe with outlier
    outliers_data=outlier.values 
    return outliers_data

In [22]:
for i in df.columns:
    if df[i].dtypes=='int64':
        li=identify_outliers(i)
        print(i,"     ",len(li))
    else:
        continue

math score       8
reading score       6
writing score       5
Total score       6


In [23]:
def detect_outlier(df,cols):
    for x in cols:
        q75,q25=np.percentile(df.loc[:,x],[75,25])
        intr_qr=q75-q25
        
        max_v =q75+(1.5*intr_qr)
        min_v =q25-(1.5*intr_qr)
        
        df.loc[df[x]<min_v,x]=np.nan
        df.loc[df[x]>max_v,x]=np.nan

In [24]:
numer=[]
cate=[]
for i in df.columns.values:
    # print(i)
    if df[i].dtypes!='object':
        numer.append(i)
    else:
        cate.append(i)

print(numer)
print(cate)

['math score', 'reading score', 'writing score', 'Total score']
['gender', 'race/ethnicity', 'parental level of education', 'lunch', 'test preparation course']


In [25]:
outlier_drop=detect_outlier(df, numer)

In [26]:
df.isnull().sum()

gender                         0
race/ethnicity                 0
parental level of education    0
lunch                          0
test preparation course        0
math score                     8
reading score                  6
writing score                  5
Total score                    6
dtype: int64

In [27]:
df.describe()

math score  reading score  writing score  Total score
count  992.000000     994.000000     995.000000   994.000000
mean    66.480847      69.443662      68.306533   204.159960
std     14.559999      14.205560      14.804953    41.456338
min     27.000000      29.000000      27.000000    88.000000
25%     57.000000      60.000000      58.000000   175.000000
50%     66.000000      70.000000      69.000000   206.000000
75%     77.000000      79.750000      79.000000   233.750000
max    100.000000     100.000000     100.000000   300.000000

In [28]:
df['math score'].fillna(df['math score'].mean(), inplace=True)
df['reading score'].fillna(df['reading score'].mean(), inplace=True)
df['writing score'].fillna(df['writing score'].mean(), inplace=True)
df['Total score'].fillna(df['Total score'].mean(), inplace=True)

In [29]:
df.isnull().sum()

gender                         0
race/ethnicity                 0
parental level of education    0
lunch                          0
test preparation course        0
math score                     0
reading score                  0
writing score                  0
Total score                    0
dtype: int64

In [30]:
for i in df.columns.values:
    print(df[i].value_counts())

gender
female    518
male      482
Name: count, dtype: int64
race/ethnicity
group C    319
group D    262
group B    190
group E    140
group A     89
Name: count, dtype: int64
parental level of education
some college          226
associate's degree    222
high school           196
some high school      179
bachelor's degree     118
master's degree        59
Name: count, dtype: int64
lunch
standard        645
free/reduced    355
Name: count, dtype: int64
test preparation course
none         642
completed    358
Name: count, dtype: int64
math score
65.0    36
62.0    35
69.0    32
59.0    32
61.0    27
        ..
27.0     2
95.0     2
36.0     2
33.0     1
28.0     1
Name: count, Length: 74, dtype: int64
reading score
72.0    34
74.0    33
64.0    32
67.0    30
73.0    30
        ..
38.0     2
31.0     2
29.0     2
32.0     1
40.0     1
Name: count, Length: 68, dtype: int64
writing score
74.0    35
70.0    33
68.0    31
73.0    28
80.0    27
        ..
37.0     2
32.0     2
28.0     1
3

### result column

In [31]:
df['percentage'] = (df['Total score'] / 300) * 100
df['result'] = df['percentage'].apply(lambda x: 'pass' if x >= 37 else 'fail')

In [32]:
df['result'] = df['result'].map({'fail': 0, 'pass': 1})

In [33]:
df.head()

gender race/ethnicity parental level of education         lunch  \
0  female        group B           bachelor's degree      standard   
1  female        group C                some college      standard   
2  female        group B             master's degree      standard   
3    male        group A          associate's degree  free/reduced   
4    male        group C                some college      standard   

  test preparation course  math score  reading score  writing score  \
0                    none        72.0           72.0           74.0   
1               completed        69.0           90.0           88.0   
2                    none        90.0           95.0           93.0   
3                    none        47.0           57.0           44.0   
4                    none        76.0           78.0           75.0   

   Total score  percentage  result  
0        218.0   72.666667       1  
1        247.0   82.333333       1  
2        278.0   92.666667       1  
3        148.0   49.333333       1  
4        229.0   76.333333       1

In [34]:
df[df['result']==0]

gender race/ethnicity parental level of education         lunch  \
91     male        group C                 high school  free/reduced   
145  female        group C                some college  free/reduced   
211    male        group C                some college  free/reduced   
338  female        group B            some high school  free/reduced   
363  female        group D            some high school  free/reduced   
466  female        group D          associate's degree  free/reduced   
555  female        group C                some college  free/reduced   
601  female        group C                 high school      standard   
787  female        group B                some college      standard   
842  female        group B                 high school  free/reduced   
895  female        group E            some high school  free/reduced   
896    male        group B                 high school  free/reduced   

    test preparation course  math score  reading score  writing score  \
91                     none   27.000000      34.000000           36.0   
145                    none   66.480847      39.000000           33.0   
211                    none   35.000000      69.443662           27.0   
338                    none   66.480847      38.000000           27.0   
363                    none   27.000000      34.000000           32.0   
466                    none   66.480847      31.000000           38.0   
555                    none   32.000000      39.000000           33.0   
601                    none   29.000000      29.000000           30.0   
787                    none   66.480847      38.000000           32.0   
842               completed   66.480847      44.000000           36.0   
895                    none   32.000000      34.000000           38.0   
896                    none   36.000000      29.000000           27.0   

     Total score  percentage  result  
91          97.0   32.333333       0  
145         94.0   31.333333       0  
211         90.0   30.000000       0  
338         89.0   29.666667       0  
363         93.0   31.000000       0  
466         95.0   31.666667       0  
555        104.0   34.666667       0  
601         88.0   29.333333       0  
787         89.0   29.666667       0  
842        103.0   34.333333       0  
895        104.0   34.666667       0  
896         92.0   30.666667       0

### label encoding

In [35]:
from sklearn.preprocessing import LabelEncoder

In [36]:
lb=LabelEncoder()

In [37]:
df.dtypes

gender                          object
race/ethnicity                  object
parental level of education     object
lunch                           object
test preparation course         object
math score                     float64
reading score                  float64
writing score                  float64
Total score                    float64
percentage                     float64
result                           int64
dtype: object

In [38]:
df['gender']=lb.fit_transform(df['gender'])
df['race/ethnicity']=lb.fit_transform(df['race/ethnicity'])
df['lunch']=lb.fit_transform(df['lunch'])
df['test preparation course']=lb.fit_transform(df['test preparation course'])
df['parental level of education']=lb.fit_transform(df['parental level of education'])

In [39]:
df.head()

gender  race/ethnicity  parental level of education  lunch  \
0       0               1                            1      1   
1       0               2                            4      1   
2       0               1                            3      1   
3       1               0                            0      0   
4       1               2                            4      1   

   test preparation course  math score  reading score  writing score  \
0                        1        72.0           72.0           74.0   
1                        0        69.0           90.0           88.0   
2                        1        90.0           95.0           93.0   
3                        1        47.0           57.0           44.0   
4                        1        76.0           78.0           75.0   

   Total score  percentage  result  
0        218.0   72.666667       1  
1        247.0   82.333333       1  
2        278.0   92.666667       1  
3        148.0   49.333333       1  
4        229.0   76.333333       1

In [40]:
for i in df.columns.values:
    print(df[i].value_counts())

gender
0    518
1    482
Name: count, dtype: int64
race/ethnicity
2    319
3    262
1    190
4    140
0     89
Name: count, dtype: int64
parental level of education
4    226
0    222
2    196
5    179
1    118
3     59
Name: count, dtype: int64
lunch
1    645
0    355
Name: count, dtype: int64
test preparation course
1    642
0    358
Name: count, dtype: int64
math score
65.0    36
62.0    35
69.0    32
59.0    32
61.0    27
        ..
27.0     2
95.0     2
36.0     2
33.0     1
28.0     1
Name: count, Length: 74, dtype: int64
reading score
72.0    34
74.0    33
64.0    32
67.0    30
73.0    30
        ..
38.0     2
31.0     2
29.0     2
32.0     1
40.0     1
Name: count, Length: 68, dtype: int64
writing score
74.0    35
70.0    33
68.0    31
73.0    28
80.0    27
        ..
37.0     2
32.0     2
28.0     1
35.0     1
30.0     1
Name: count, Length: 73, dtype: int64
Total score
204.0    15
232.0    14
198.0    14
205.0    13
214.0    12
         ..
272.0     1
94.0      1
277.0     1
9

### change dtype

In [41]:
df.dtypes

gender                           int32
race/ethnicity                   int32
parental level of education      int32
lunch                            int32
test preparation course          int32
math score                     float64
reading score                  float64
writing score                  float64
Total score                    float64
percentage                     float64
result                           int64
dtype: object

In [42]:
df['math score']=df['math score'].astype('int32')
df['reading score']=df['reading score'].astype('int32')
df['writing score']=df['writing score'].astype('int32')
df['Total score']=df['Total score'].astype('int32')

In [43]:
df.dtypes

gender                           int32
race/ethnicity                   int32
parental level of education      int32
lunch                            int32
test preparation course          int32
math score                       int32
reading score                    int32
writing score                    int32
Total score                      int32
percentage                     float64
result                           int64
dtype: object

In [44]:
for i in df.columns.values:
    print(df[i].value_counts())

gender
0    518
1    482
Name: count, dtype: int64
race/ethnicity
2    319
3    262
1    190
4    140
0     89
Name: count, dtype: int64
parental level of education
4    226
0    222
2    196
5    179
1    118
3     59
Name: count, dtype: int64
lunch
1    645
0    355
Name: count, dtype: int64
test preparation course
1    642
0    358
Name: count, dtype: int64
math score
65    36
62    35
69    32
59    32
66    32
      ..
30     2
27     2
34     2
33     1
28     1
Name: count, Length: 73, dtype: int64
reading score
72    34
74    33
64    32
67    30
73    30
      ..
38     2
31     2
29     2
32     1
40     1
Name: count, Length: 67, dtype: int64
writing score
68    36
74    35
70    33
73    28
80    27
      ..
37     2
98     2
35     1
28     1
30     1
Name: count, Length: 72, dtype: int64
Total score
204    21
198    14
232    14
205    13
214    12
       ..
299     1
114     1
272     1
124     1
133     1
Name: count, Length: 189, dtype: int64
percentage
68.000000    15

In [45]:
df.columns

Index(['gender', 'race/ethnicity', 'parental level of education', 'lunch',
       'test preparation course', 'math score', 'reading score',
       'writing score', 'Total score', 'percentage', 'result'],
      dtype='object')

### dividng input and output features

In [46]:
X = df.drop(columns=['math score', 'reading score','writing score','Total score', 'percentage','result'])  # or keep some scores
y = df['result']

In [47]:
X_train, X_test, y_train,y_test = train_test_split(X, y, test_size=0.30, random_state=42)

In [48]:
sc=StandardScaler()

In [49]:
X_train_scaled=sc.fit_transform(X_train)

In [50]:
X_test_scaled=sc.transform(X_test)

## Logistic

#### applying logistic regression

In [51]:
lr=LogisticRegression()

In [52]:
lr.fit(X_train_scaled, y_train)

LogisticRegression()

In [53]:
y_pred_lr=lr.predict(X_test_scaled)

#### metrics of logistic regression

In [54]:
lr_score=accuracy_score(y_test, y_pred_lr)
lr_score

0.9833333333333333

In [55]:
lr.score(X_train_scaled,y_train)

0.99

In [56]:
fpr_lr, tpr_lr, _ = roc_curve(y_test, y_pred_lr)
auc_lr = roc_auc_score(y_test, y_pred_lr)
auc_lr

0.5

In [57]:
lr_cm=confusion_matrix(y_test, y_pred_lr)
lr_cm

array([[  0,   5],
       [  0, 295]], dtype=int64)

In [58]:
print(classification_report(y_test, y_pred_lr))

              precision    recall  f1-score   support

           0       0.00      0.00      0.00         5
           1       0.98      1.00      0.99       295

    accuracy                           0.98       300
   macro avg       0.49      0.50      0.50       300
weighted avg       0.97      0.98      0.98       300



C:\Users\91876\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\metrics\_classification.py:1509: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
C:\Users\91876\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\metrics\_classification.py:1509: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
C:\Users\91876\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\metrics\_classification.py:1509: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, mo

In [59]:
print(precision_score(y_test, y_pred_lr))
print(recall_score(y_test, y_pred_lr))
print(f1_score(y_test, y_pred_lr))

0.9833333333333333
1.0
0.9915966386554622


### saving the file

In [60]:
import pickle

In [61]:
with open('result_model.pkl', 'wb') as model_file:
    pickle.dump(lr, model_file)

with open('result_scaler.pkl', 'wb') as scaler_file:
    pickle.dump(sc, scaler_file)

### code for prediction

In [62]:
import pickle 
import numpy as np

In [63]:
with open('result_model.pkl', 'rb') as model_file:
    model=pickle.load(model_file)

with open('result_scaler.pkl', 'rb') as scaler_file:
    scaler=pickle.load(scaler_file)

In [64]:
# new_dp=[6,148,72,35,0,33.6,0.627,50]
new_dp=[0,1,1,1,1]

In [65]:
scaled_dp=scaler.transform([new_dp])

C:\Users\91876\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(


In [66]:
scaled_dp

array([[-0.93094934, -1.05104603, -0.8038796 ,  0.72460642,  0.74072435]])

In [67]:
prediction=model.predict(scaled_dp)

In [68]:
prediction

array([1], dtype=int64)

In [69]:
if prediction[0]==1:
    print('pass')
else:
    print('fail')

pass
